spring:
  jpa:
    show-sql: false
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users-db
    username: users-postgres-user
    password: users-postgres-pwd
  flyway:
    baseline-on-migrate: true
    schemas: 'flyway'

server:
  port: 8080
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:Fi@p-@lur@-2ADJT}
