version: '3.1'

services:
  customers-db:
    container_name: postgresql-customers
    image: postgres:latest
    environment:
      POSTGRES_DB: customers-db
      POSTGRES_USER: customer-postgres-user
      POSTGRES_PASSWORD: customer-postgres-pwd
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgres
    networks:
      - hackaton-postgres-network

networks:
  hackaton-postgres-network:
    driver: bridge
