version: '3.1'

services:
  user-db:
    container_name: postgresql-users
    image: postgres:latest
    environment:
      POSTGRES_DB: users-db
      POSTGRES_USER: users-postgres-user
      POSTGRES_PASSWORD: users-postgres-pwd
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres
    networks:
      - hackaton-postgres-network

networks:
  hackaton-postgres-network:
    driver: bridge
